# Generated by Django 2.1.7 on 2019-05-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_fullname',
            field=models.CharField(default='', editable=False, max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True,
                                      help_text='Designates whether the user can log into this admin site.',
                                      verbose_name='允许登录'),
        ),
    ]
