# Generated by Django 2.1.7 on 2019-05-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='cascade',
            new_name='is_cascade',
        ),
    ]
