# Generated by Django 2.1.7 on 2019-05-09 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import teaching.models


class Migration(migrations.Migration):
    dependencies = [
        # ('info', '0005_auto_20190509_2008'),
        ('teaching', '0001_initial'),
    ]

    operations = [

    ]
