# Generated by Django 2.1.7 on 2019-02-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='atv_type',
            field=models.CharField(choices=[('集中学习', '集中学习'), ('集中教育', '集中教育'), ('个人自学', '个人自学'), ('其他', '其他')], default='集中学习', max_length=10, verbose_name='活动类型'),
        ),
    ]
