# Generated by Django 2.1.7 on 2019-05-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teaching', '0002_auto_20190509_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='activity',
            name='atv_type',
            field=models.CharField(choices=[('主题党日/党课', '主题党日/党课'), ('讲座/培训', '讲座/培训'), ('其他', '其他')], max_length=10,
                                   verbose_name='活动类型'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='branch',
            field=models.ManyToManyField(to='info.Branch', verbose_name='主办单位/党支部'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开展时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='活动主题'),
        ),
    ]
