# Generated by Django 2.2.1 on 2019-05-17 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20190517_0309'),
        ('teaching', '0003_auto_20190515_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='should_phase',
            field=models.ManyToManyField(blank=True, to='teaching.Phase', verbose_name='必须参与的发展阶段'),
        ),
        migrations.CreateModel(
            name='AskForLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '缺席'), (1, '请假')], default=0, verbose_name='状态')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.Activity', verbose_name='活动主题')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Member', verbose_name='学号')),
            ],
            options={
                'verbose_name': '请假、缺席统计',
                'verbose_name_plural': '请假、缺席统计',
                'ordering': ('member', '-activity'),
                'abstract': False,
                'unique_together': {('activity', 'member')},
            },
        ),
    ]
