# Generated by Django 2.1.7 on 2019-05-17 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20190517_0021'),
        ('teaching', '0003_auto_20190515_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskForLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '缺席'), (1, '请假')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '请假、缺席统计',
                'verbose_name_plural': '请假、缺席统计',
                'ordering': ('member', '-activity'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='other_people',
            field=models.ManyToManyField(blank=True, to='info.Member', verbose_name='必须参与的成员'),
        ),
        migrations.AddField(
            model_name='askforleave',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.Activity', verbose_name='活动主题'),
        ),
        migrations.AddField(
            model_name='askforleave',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Member', verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='activity',
            name='should_phase',
            field=models.ManyToManyField(blank=True, to='teaching.Phase', verbose_name='必须参与的发展阶段'),
        ),
        migrations.AlterUniqueTogether(
            name='askforleave',
            unique_together={('activity', 'member')},
        ),
    ]
