# Generated by Django 2.1.7 on 2019-05-12 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import teaching.models


class Migration(migrations.Migration):
    dependencies = [
        ('teaching', '0003_auto_20190510_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='checkin_qr',
            field=teaching.models.NullableImageField(blank=True, editable=False, null=True,
                                                     upload_to=teaching.models.upload_to, verbose_name='签到二维码'),
        ),
    ]
