# Generated by Django 2.1.7 on 2019-05-12 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('teaching', '0004_auto_20190512_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField()),
                ('netid', models.IntegerField()),
                ('ip', models.CharField(max_length=50)),
            ],
        ),
    ]
