# Generated by Django 2.1.7 on 2019-05-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_auto_20190517_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='other_people',
        ),
    ]
