# Generated by Django 2.1.7 on 2019-05-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_remove_activity_other_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askforleave',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '缺席'), (1, '请假')], default=0, verbose_name='状态'),
        ),
    ]
