# Generated by Django 2.1.7 on 2019-05-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20190530_2334'),
        ('teaching', '0006_auto_20190517_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='should_phase',
            field=models.ManyToManyField(blank=True, to='teaching.Phase', verbose_name='参与成员'),
        ),
        migrations.AlterUniqueTogether(
            name='sharing',
            unique_together={('member', 'title')},
        ),
    ]
