# Generated by Django 2.1.7 on 2019-05-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0007_auto_20190530_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='other_people',
        ),
        migrations.AddField(
            model_name='sharing',
            name='impression_digest',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
