# Generated by Django 2.1.5 on 2019-02-01 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('branch_name', models.CharField(db_index=True, max_length=50)),
                ('netid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('birth_date', models.DateField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('group', models.CharField(max_length=20)),
                ('place_birth', models.CharField(max_length=50)),
                ('major_in', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('branch_name', 'netid'),
            },
        ),
        migrations.CreateModel(
            name='InspectedMember',
            fields=[
                ('netid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='processJoining.Member')),
                ('is_member_CYL', models.BooleanField(default=False)),
                ('constitution_group_date', models.DateField(max_length=10)),
                ('application_date', models.DateField(max_length=10)),
                ('activist_date', models.DateField(max_length=10)),
                ('league_promotion_date', models.DateField(max_length=10)),
                ('democratic_appraisal_date', models.DateField(max_length=10)),
                ('political_check_done', models.BooleanField(default=False)),
                ('key_develop_person_date', models.DateField(max_length=10)),
                ('graduated_party_school_date', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProbationaryMember',
            fields=[
                ('netid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='processJoining.InspectedMember')),
                ('recommenders_date', models.DateField(max_length=10)),
                ('recommenders', models.CharField(max_length=50)),
                ('autobiography_done', models.BooleanField(default=False)),
                ('application_form_done', models.BooleanField(default=False)),
                ('first_branch_conference', models.DateField(max_length=10)),
                ('pro_conversation_date', models.DateField(max_length=10)),
                ('talker', models.CharField(max_length=50)),
                ('probationary_approval_date', models.DateField(max_length=10)),
                ('oach_date', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FullMember',
            fields=[
                ('netid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='processJoining.ProbationaryMember')),
                ('application_fullmember_date', models.DateField(max_length=10)),
                ('second_branch_conference', models.DateField(max_length=10)),
                ('fullmember_approval_date', models.DateField(max_length=10)),
            ],
        ),
    ]
