# Generated by Django 2.1.7 on 2019-05-15 16:19

import DjangoUeditor.models
import common.storage
from django.db import migrations, models
import django.db.models.deletion
import work.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('入党积极分子', '入党积极分子'), ('重点发展对象', '重点发展对象'), ('预备党员', '预备党员'), ('正式党员', '正式党员'), ('首次组织谈话', '首次组织谈话')], max_length=50, unique=True, verbose_name='阶段')),
                ('notice', models.FileField(help_text='发送邮件时，这份材料在附件中。', storage=common.storage.OverwriteStorage(), upload_to=work.models.upload_to2, verbose_name='通知')),
                ('files', models.FileField(blank=True, help_text='发送邮件时，这份材料在正文的链接中。', null=True, storage=common.storage.OverwriteStorage(), upload_to=work.models.upload_to2, verbose_name='相关材料')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(editable=False, max_length=50, verbose_name='作者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_edit_time', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('file', models.FileField(blank=True, null=True, storage=common.storage.OverwriteStorage(), upload_to=work.models.upload_to, verbose_name='文件')),
                ('branch', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='info.Branch', verbose_name='党支部名称')),
            ],
            options={
                'verbose_name': '工作笔记',
                'verbose_name_plural': '工作笔记',
                'ordering': ('-last_edit_time', 'author', 'create_time', 'title'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(editable=False, max_length=50, verbose_name='作者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_edit_time', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('file', models.FileField(storage=common.storage.OverwriteStorage(), upload_to=work.models.upload_to, verbose_name='文件')),
                ('branch', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='info.Branch', verbose_name='党支部名称')),
            ],
            options={
                'verbose_name': '规章制度',
                'verbose_name_plural': '规章制度',
                'ordering': ('-last_edit_time', 'author', 'create_time', 'title'),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('title', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('title', 'author')},
        ),
    ]
