# Generated by Django 2.1.5 on 2019-02-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
    ]
