# Generated by Django 2.1.5 on 2019-02-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190211_1142'),
    ]

    operations = [
    ]
