# Generated by Django 2.1.7 on 2019-02-19 16:24

from django.db import migrations, models
import django.db.models.deletion
import info.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(max_length=8, verbose_name='学号')),
                ('application_type', models.CharField(choices=[('入党申请人', '入党申请'), ('入党积极分子', '入党积极分子'), ('重点发展对象', '重点发展对象'), ('预备党员', '预备党员'), ('正式党员', '正式党员')], max_length=20, verbose_name='申请成为')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50, verbose_name='名称')),
                ('date_create', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='成立日期')),
            ],
            options={
                'verbose_name': '党支部',
                'verbose_name_plural': '党支部',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_1', models.CharField(choices=[('birth_date', '出生时间'), ('youth_league_date', '加入共青团时间'), ('constitution_group_date', '参加党章学习小组时间'), ('application_date', '递交入党申请书时间'), ('activist_date', '确定为入党积极分子时间'), ('league_promotion_date', '团支部推优（重点发展对象）时间'), ('democratic_appraisal_date', '民主评议时间'), ('political_check_date', '政治审查时间'), ('key_develop_person_date', '确认为重点发展对象时间'), ('graduated_party_school_date', '党校培训结业时间'), ('recommenders_date', '确认入党介绍人时间'), ('autobiography_date', '填写自传时间'), ('application_form_date', '填写入党志愿书时间'), ('first_branch_conference', '支部大会通过成为预备党员时间'), ('pro_conversation_date', '入党谈话时间'), ('probationary_approval_date', '党委批准成为预备党员时间'), ('oach_date', '入党宣誓时间'), ('application_fullmember_date', '递交转正申请书时间'), ('second_branch_conference', '支部大会通过成为正式党员时间'), ('fullmember_approval_date', '党委批准成为正式党员时间')], max_length=50, verbose_name='from')),
                ('to', models.CharField(choices=[('birth_date', '出生时间'), ('youth_league_date', '加入共青团时间'), ('constitution_group_date', '参加党章学习小组时间'), ('application_date', '递交入党申请书时间'), ('activist_date', '确定为入党积极分子时间'), ('league_promotion_date', '团支部推优（重点发展对象）时间'), ('democratic_appraisal_date', '民主评议时间'), ('political_check_date', '政治审查时间'), ('key_develop_person_date', '确认为重点发展对象时间'), ('graduated_party_school_date', '党校培训结业时间'), ('recommenders_date', '确认入党介绍人时间'), ('autobiography_date', '填写自传时间'), ('application_form_date', '填写入党志愿书时间'), ('first_branch_conference', '支部大会通过成为预备党员时间'), ('pro_conversation_date', '入党谈话时间'), ('probationary_approval_date', '党委批准成为预备党员时间'), ('oach_date', '入党宣誓时间'), ('application_fullmember_date', '递交转正申请书时间'), ('second_branch_conference', '支部大会通过成为正式党员时间'), ('fullmember_approval_date', '党委批准成为正式党员时间')], max_length=50, verbose_name='to')),
                ('days', models.IntegerField(choices=[(30, '1个月'), (60, '2个月'), (90, '3个月'), (180, '半年'), (365, '1年'), (6570, '18年'), (1, '1天'), (2, '2天'), (3, '3天'), (4, '4天'), (5, '5天'), (6, '6天'), (7, '7天'), (8, '8天'), (9, '9天'), (10, '10天')], verbose_name='周期')),
            ],
            options={
                'verbose_name': '发展流程依赖',
                'verbose_name_plural': '发展流程依赖',
                'ordering': ('from_1', 'to', 'days'),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('netid', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='姓名')),
                ('birth_date', models.DateField(max_length=10, verbose_name='出生时间')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=1, verbose_name='性别')),
                ('group', models.CharField(max_length=20, verbose_name='民族')),
                ('family_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='家庭住址')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='联系电话')),
                ('credit_card_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号码')),
                ('major_in', models.CharField(max_length=30, verbose_name='当前专业（全称）')),
                ('youth_league_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='加入共青团时间')),
                ('constitution_group_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='参加党章学习小组时间')),
                ('application_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='递交入党申请书时间')),
                ('activist_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='确定为入党积极分子时间')),
                ('league_promotion_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='团支部推优（重点发展对象）时间')),
                ('democratic_appraisal_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='民主评议时间')),
                ('political_check_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='政治审查时间')),
                ('key_develop_person_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='确认为重点发展对象时间')),
                ('graduated_party_school_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='党校培训结业时间')),
                ('recommenders_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='确认入党介绍人时间')),
                ('recommenders', models.CharField(blank=True, max_length=50, null=True, verbose_name='入党介绍人')),
                ('autobiography_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='填写自传时间')),
                ('application_form_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='填写入党志愿书时间')),
                ('first_branch_conference', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='支部大会通过成为预备党员时间')),
                ('pro_conversation_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='入党谈话时间')),
                ('talker', models.CharField(blank=True, max_length=50, null=True, verbose_name='入党谈话人')),
                ('probationary_approval_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='党委批准成为预备党员时间')),
                ('oach_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='入党宣誓时间')),
                ('application_fullmember_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='递交转正申请书时间')),
                ('second_branch_conference', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='支部大会通过成为正式党员时间')),
                ('fullmember_approval_date', info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='党委批准成为正式党员时间')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Branch', verbose_name='党支部')),
            ],
            options={
                'verbose_name': '成员信息',
                'verbose_name_plural': '成员信息',
                'ordering': ('branch', 'netid'),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
                'ordering': ('name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('from_1', 'to')},
        ),
        migrations.AddField(
            model_name='branch',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.School', verbose_name='学院'),
        ),
    ]
