# Generated by Django 2.1.7 on 2019-02-28 11:37

from django.db import migrations, models
import info.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='credit_card_id',
        ),
        migrations.AddField(
            model_name='member',
            name='first_talk_date',
            field=info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='首次组织谈话时间'),
        ),
        migrations.AlterField(
            model_name='application',
            name='netid',
            field=models.IntegerField(verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='from_1',
            field=models.CharField(choices=[('birth_date', '出生时间'), ('youth_league_date', '加入共青团时间'), ('constitution_group_date', '参加党章学习小组时间'), ('application_date', '递交入党申请书时间'), ('first_talk_date', '首次组织谈话时间'), ('activist_date', '确定为入党积极分子时间'), ('league_promotion_date', '团支部推优（重点发展对象）时间'), ('democratic_appraisal_date', '民主评议时间'), ('political_check_date', '政治审查时间'), ('key_develop_person_date', '确定为重点发展对象时间'), ('graduated_party_school_date', '党校培训结业时间'), ('recommenders_date', '确定入党介绍人时间'), ('autobiography_date', '填写自传时间'), ('application_form_date', '填写入党志愿书时间'), ('first_branch_conference', '支部大会通过成为预备党员时间'), ('pro_conversation_date', '入党谈话时间'), ('probationary_approval_date', '党委批准成为预备党员时间'), ('oach_date', '入党宣誓时间'), ('application_fullmember_date', '递交转正申请书时间'), ('second_branch_conference', '支部大会通过成为正式党员时间'), ('fullmember_approval_date', '党委批准成为正式党员时间')], max_length=50, verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='to',
            field=models.CharField(choices=[('birth_date', '出生时间'), ('youth_league_date', '加入共青团时间'), ('constitution_group_date', '参加党章学习小组时间'), ('application_date', '递交入党申请书时间'), ('first_talk_date', '首次组织谈话时间'), ('activist_date', '确定为入党积极分子时间'), ('league_promotion_date', '团支部推优（重点发展对象）时间'), ('democratic_appraisal_date', '民主评议时间'), ('political_check_date', '政治审查时间'), ('key_develop_person_date', '确定为重点发展对象时间'), ('graduated_party_school_date', '党校培训结业时间'), ('recommenders_date', '确定入党介绍人时间'), ('autobiography_date', '填写自传时间'), ('application_form_date', '填写入党志愿书时间'), ('first_branch_conference', '支部大会通过成为预备党员时间'), ('pro_conversation_date', '入党谈话时间'), ('probationary_approval_date', '党委批准成为预备党员时间'), ('oach_date', '入党宣誓时间'), ('application_fullmember_date', '递交转正申请书时间'), ('second_branch_conference', '支部大会通过成为正式党员时间'), ('fullmember_approval_date', '党委批准成为正式党员时间')], max_length=50, verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='出生时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='男', max_length=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='member',
            name='key_develop_person_date',
            field=info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='确定为重点发展对象时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='major_in',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='当前专业（全称）'),
        ),
        migrations.AlterField(
            model_name='member',
            name='netid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='member',
            name='recommenders_date',
            field=info.models.NullableDateField(blank=True, default=None, max_length=10, null=True, verbose_name='确定入党介绍人时间'),
        ),
    ]
