# Generated by Django 2.1.7 on 2019-03-14 15:41

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
