# Generated by Django 2.1.7 on 2019-03-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_branch_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='detail',
        ),
    ]
