# Generated by Django 2.1.7 on 2019-05-08 22:22

from django.db import migrations, models
import info.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0003_remove_branch_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='archive_date',
            field=info.models.NullableDateField(blank=True, default=None, max_length=10, null=True,
                                                verbose_name='转档案馆时间'),
        ),
        migrations.AddField(
            model_name='member',
            name='deffer_employ_date',
            field=info.models.NullableDateField(blank=True, default=None, max_length=10, null=True,
                                                verbose_name='暂缓就业时间'),
        ),
        migrations.AddField(
            model_name='member',
            name='out_date',
            field=info.models.NullableDateField(blank=True, default=None, max_length=10, null=True,
                                                verbose_name='关系转出时间'),
        ),
        migrations.AddField(
            model_name='member',
            name='out_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='转出单位'),
        )
    ]
