# Generated by Django 2.2.1 on 2019-05-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0004_auto_20190515_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='oldmember',
            name='contacts',
        ),
        migrations.AddField(
            model_name='member',
            name='out_type',
            field=models.CharField(blank=True, choices=[('D.就业', 'D.就业'), ('G.境内升学', 'G.境内升学'), ('A.出国留学', 'A.出国留学')],
                                   max_length=20, null=True, verbose_name='转出类型'),
        ),
        migrations.AddField(
            model_name='oldmember',
            name='out_type',
            field=models.CharField(blank=True, choices=[('D.就业', 'D.就业'), ('G.境内升学', 'G.境内升学'), ('A.出国留学', 'A.出国留学')],
                                   max_length=20, null=True, verbose_name='转出类型'),
        ),
        migrations.AlterField(
            model_name='member',
            name='out_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='去向单位'),
        ),
        migrations.AlterField(
            model_name='oldmember',
            name='out_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='去向单位'),
        ),
    ]
