# Generated by Django 2.1.7 on 2019-05-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20190516_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='out_type',
            field=models.CharField(blank=True, choices=[('D.就业', 'D.就业'), ('G.境内升学', 'G.境内升学'), ('A.出国留学', 'A.出国留学'), ('无', '无')], max_length=20, null=True, verbose_name='转出类型'),
        ),
        migrations.AlterField(
            model_name='oldmember',
            name='out_type',
            field=models.CharField(blank=True, choices=[('D.就业', 'D.就业'), ('G.境内升学', 'G.境内升学'), ('A.出国留学', 'A.出国留学'), ('无', '无')], max_length=20, null=True, verbose_name='转出类型'),
        ),
    ]
