# Generated by Django 2.1.7 on 2019-05-10 05:38

from django.db import migrations, models
import info.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0005_auto_20190509_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phase',
            field=models.IntegerField(
                choices=[(0, '无'), (1, '提交入党申请'), (2, '积极分子'), (3, '发展对象'), (4, '预备党员'), (5, '正式党员')], default=0,
                verbose_name='发展阶段'),
        )
    ]
