# Generated by Django 2.2.1 on 2019-05-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20190516_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='out_type',
            field=models.CharField(blank=True, choices=[('C.出国境升学', 'C.出国境升学'), ('D.就业', 'D.就业'), ('E.暂缓就业', 'E.暂缓就业'), ('F.延毕', 'F.延毕'), ('G.境内升学', 'G.境内升学'), ('Z.无', 'Z.无')], max_length=20, null=True, verbose_name='转出类型'),
        ),
        migrations.AlterField(
            model_name='member',
            name='years',
            field=models.IntegerField(default=4, help_text='转专业或休学时可以增加学年制。', verbose_name='学年制'),
        ),
        migrations.AlterField(
            model_name='oldmember',
            name='out_type',
            field=models.CharField(blank=True, choices=[('C.出国境升学', 'C.出国境升学'), ('D.就业', 'D.就业'), ('E.暂缓就业', 'E.暂缓就业'), ('F.延毕', 'F.延毕'), ('G.境内升学', 'G.境内升学'), ('Z.无', 'Z.无')], max_length=20, null=True, verbose_name='转出类型'),
        ),
        migrations.AlterField(
            model_name='oldmember',
            name='years',
            field=models.IntegerField(default=4, help_text='转专业或休学时可以增加学年制。', verbose_name='学年制'),
        ),
    ]
