# Generated by Django 2.1.7 on 2019-05-10 09:38

from django.db import migrations, models
import info.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0006_auto_20190510_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(max_length=10, verbose_name='出生时间'),
        )
    ]
