# Generated by Django 2.1.7 on 2019-05-30 23:34

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20190517_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_sysu',
            field=common.models.MyBooleanField(default=True, help_text='在中山大学发展的党员，其录入的信息需严格遵循相关流程依赖。', verbose_name='是否在中山大学发展'),
        ),
        migrations.AlterField(
            model_name='member',
            name='youth_league_member',
            field=common.models.MyBooleanField(default=True, help_text='非团员发展时采用党员推荐方式。', verbose_name='是否团员'),
        ),
        migrations.AlterField(
            model_name='oldmember',
            name='is_sysu',
            field=common.models.MyBooleanField(default=True, help_text='在中山大学发展的党员，其录入的信息需严格遵循相关流程依赖。', verbose_name='是否在中山大学发展'),
        ),
        migrations.AlterField(
            model_name='oldmember',
            name='youth_league_member',
            field=common.models.MyBooleanField(default=True, help_text='非团员发展时采用党员推荐方式。', verbose_name='是否团员'),
        ),
    ]
