# Generated by Django 2.1.7 on 2019-06-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20190530_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('本科生', '本科生'), ('研究生', '研究生'), ('无', '无')], default='无', max_length=50, verbose_name='支部类型'),
        ),
    ]
